name: golpokotha
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0-143.0.dev <4.0.0"

dependencies:
  audio_session: ^0.1.18
  cupertino_icons: ^1.0.6
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  get: 4.6.6
  google_fonts: ^6.2.1
  just_audio: ^0.9.36
  image_gradient: ^0.0.2
  audio_video_progress_bar: ^2.0.2
  http: ^1.2.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9
  firebase_core_platform_interface: ^5.0.0
  # flutter_svg: ^0.22.0
  flutter_img: ^0.1.6+148
  google_sign_in: ^6.2.1
  firebase_core: ^2.27.1
  

dev_dependencies:
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/"
    - "assets/images/"