name: golpokotha
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0-143.0.dev <4.0.0"

dependencies:
  audio_session: ^0.1.18
  cupertino_icons: ^1.0.6
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  get: 4.6.6
  google_fonts: ^6.2.1
  just_audio: ^0.9.36
  rxdart: ^0.27.7

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/images/"
